In [8]:
import numpy as np

# Matrix A
A = np.array([
    [6, 1],
    [3, 4]
])


# Matrix B
B = np.array([
    [4, 1, 1],
    [1, 0, 2]
])


# Eigenvalue Decomposition of A
eigenvalues, eigenvectors = np.linalg.eig(A)

print("Eigenvalue Decomposition of A:")
print(f"Eigenvalues:\n{eigenvalues}\n")
print(f"Eigenvectors:\n{eigenvectors}\n")

# Verify: A = V @ D @ V^(-1)
D = np.diag(eigenvalues)
print("D:")
print( D)
V = eigenvectors
print("V:")
print(V)

print("V inv:")
print(np.linalg.inv(V))
A_reconstructed = V @ D @ np.linalg.inv(V)

print("Verification - A reconstructed from EVD:")
print(A_reconstructed)

Eigenvalue Decomposition of A:
Eigenvalues:
[7. 3.]

Eigenvectors:
[[ 0.70710678 -0.31622777]
 [ 0.70710678  0.9486833 ]]

D:
[[7. 0.]
 [0. 3.]]
V:
[[ 0.70710678 -0.31622777]
 [ 0.70710678  0.9486833 ]]
V inv:
[[ 1.06066017  0.35355339]
 [-0.79056942  0.79056942]]
Verification - A reconstructed from EVD:
[[6. 1.]
 [3. 4.]]


In [9]:
def checkPostiveDef( eigenvalues, name="Matrix"):
    if np.all(eigenvalues > 0):
        print("\n✓ Matrix  is POSITIVE DEFINITE")
        print("  (All eigenvalues are positive)")
    elif np.all(eigenvalues >= 0):
        print("\n✓ Matrix is POSITIVE SEMI-DEFINITE")
        print("  (All eigenvalues are non-negative, at least one is zero)")
    elif np.all(eigenvalues < 0):
        print("\n✗ Matrix  is NEGATIVE DEFINITE")
        print("  (All eigenvalues are negative)")
    else:
        print("\n✗ Matrix  is INDEFINITE")
        print("  (Has both positive and negative eigenvalues)")

In [10]:
checkPostiveDef(eigenvalues);


✓ Matrix A is POSITIVE DEFINITE
  (All eigenvalues are positive)


In [13]:
B = np.array([
    [4, 1, 1],
    [1,3, 0],
    [1, 0, 2]
])

eigenvalues_B, eigenvectors_B = np.linalg.eig(B)
print(eigenvalues_B)

checkPostiveDef(eigenvalues_B);


[4.87938524 1.46791111 2.65270364]

✓ Matrix A is POSITIVE DEFINITE
  (All eigenvalues are positive)


In [17]:
def check_positive_definiteness_sylvester(matrix, name="Matrix"):
    n = matrix.shape[0]
    is_positive_definite = True

    for k in range( 1, n+1):
        submatrix = matrix[:k,:k]
        determinant = np.linalg.det(submatrix)
        print(f"Leading principal minor {k}×{k}:")
        print(f"  Submatrix:\n{submatrix}")
        print(f"  Determinant: {determinant:.6f}")
        if determinant <= 0:
            is_positive_definite = False
            break

    if is_positive_definite:
        print(f"\n✓ {name} is POSITIVE DEFINITE (Sylvester's criterion)")
    else:
        print(f"\n✗ {name} is NOT POSITIVE DEFINITE (Sylvester's criterion)")


In [19]:
check_positive_definiteness_sylvester(A)

Leading principal minor 1×1:
  Submatrix:
[[6]]
  Determinant: 6.000000
Leading principal minor 2×2:
  Submatrix:
[[6 1]
 [3 4]]
  Determinant: 21.000000

✓ Matrix is POSITIVE DEFINITE (Sylvester's criterion)


In [20]:

check_positive_definiteness_sylvester(B)

Leading principal minor 1×1:
  Submatrix:
[[4]]
  Determinant: 4.000000
Leading principal minor 2×2:
  Submatrix:
[[4 1]
 [1 3]]
  Determinant: 11.000000
Leading principal minor 3×3:
  Submatrix:
[[4 1 1]
 [1 3 0]
 [1 0 2]]
  Determinant: 19.000000

✓ Matrix is POSITIVE DEFINITE (Sylvester's criterion)
